on:
  workflow_call:

jobs:
  test:
    name: Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [ '11', '17', '21' ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
          cache: 'gradle'
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew check -x test --console=plain --warning-mode all
